# Generated by Django 6.0.6 on 2026-06-22 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_chatsession_is_favorite_chatsession_is_pinned'),
    ]

    operations = [
        migrations.AddField(
            model_name='userxp',
            name='best_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userxp',
            name='last_login_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userxp',
            name='streak',
            field=models.IntegerField(default=0),
        ),
    ]
